// <auto-generated />
namespace EntityFrameworkLesson2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Rating_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rating_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "202107141324444_Rating_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
